// fakeStreamAgent.js
const { Response } = require('ai-agent-response');

class FakeStreamAgent {
    constructor(metadata) {
        this.delay = metadata.delay || 100; // 从metadata中获取延迟，默认为100ms
    }

    async generateReply(thread) {
        const response = new Response();
        const fakeMessage = this.generateFakeMessage(thread);
        response.setStream(this.createFakeStream(fakeMessage));
        return response;
    }

    generateFakeMessage(thread) {
        const lastMessage = thread.messages[thread.messages.length - 1];
        return `This is a stream fake response to: "${lastMessage.text}". It was generated by FakeAgent.`;
    }

    async *createFakeStream(message) {
        const words = message.split(' ');
        for (const word of words) {
            yield word + ' ';
            await new Promise(resolve => setTimeout(resolve, this.delay));
        }
    }
}

module.exports = FakeStreamAgent;